### ISSUE TITLE
@media print broken attribute 

### ISSUE THREAD

**Issue by claudio-moya** [kesla/css2json#5]
Hi guys, 

Thanx for this library has been a very good tool for my team's projects.
It works fine on our project but today I was testing the `prism` library and I got a broken attribute.

This is the code:

```css
@media print {
	code[class*="language-"],
	pre[class*="language-"] {
		text-shadow: none;
	}
}
```

Output
```js
'@media print': {
    'code[class*=language-],pre[class*=language-]{text-shadow': 'none'
  },
  '}pre[class*=language-]': { '': '}pre[class*=language-]{' },
```

This is the original css file:

https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/themes/prism.css

Please take a look to it, and thanx again!
